export const CHANGE_CATALOG_FILTER = 'CHANGE_CATALOG_FILTER';
export const CHANGE_SEARCH_FILTER = 'CHANGE_SEARCH_FILTER';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST';
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_FAILURE = 'POST_ORDER_FAILURE';
export const RESET_CART = 'RESET_CART';
